name: find_a_donor
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  line_icons: ^0.2.0
  flutter_svg: ^0.14.1
  device_preview: ^0.2.6
  flutter_screenutil: ^1.0.1
  dartz: ^0.8.9
  flutter_bloc: ^3.1.0
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/images/home_page/bg/
    - assets/images/register_phone_page/
    - assets/images/register_otp_page/
    - assets/images/done_page/
    - assets/images/reset_password_phone_page/

    - assets/icons/home_page/header/
    - assets/icons/home_page/action-buttons/
    - assets/icons/home_page/bottom-navigation/
    - assets/icons/register_phone_page/
    - assets/icons/register_otp_page/
    - assets/icons/done_page/
    - assets/icons/reset_password_phone_page/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-semiBold.ttf
          weight: 600
